# Generated by Django 3.2.25 on 2026-04-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_useraccount_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_slug', models.CharField(max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_holder_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=120)),
                ('account_type', models.CharField(max_length=40)),
                ('debit_card_last6', models.CharField(blank=True, max_length=6)),
                ('expiry_date', models.CharField(blank=True, max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('upi_pin', models.CharField(blank=True, max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_banks', to='core.useraccount')),
            ],
        ),
    ]
