# Generated by Django 3.2.25 on 2026-04-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_upi_id', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='dashboard.linkedbankaccount')),
                ('sender_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='dashboard.linkedbankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
