# Generated by Django 3.2.25 on 2026-04-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccount_profile_fields'),
        ('dashboard', '0002_auto_20260409_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_identifier', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_money_requests', to='dashboard.linkedbankaccount')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_money_requests', to='core.useraccount')),
                ('requester_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_money_requests', to='dashboard.linkedbankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
